title: Sympony of Death

description: >
    Symphony of Death is a collection of experiments
    translating Halo 5 match events into
    interactive instruments using WebGL and Web Audio.

baseurl: "" # the subpath of your site, e.g. /blog

markdown: kramdown

exclude: [
    '*.rb',
    'design',
    'documentation',
    'node_modules',
    'LICENSE',
    'package.json',
    'README.md',
    'server',
    'src',
    'webpack.config.js',
]